name: Daily Cyber
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests feedparser

      - name: Run script
        run: python cyber_bulletin.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add reports/
          if git diff --cached --quiet; then
            echo "Aucun changement à commiter."
          else
            git commit -m "Archive: $(date +'%Y-%m-%d')"
            git push
          fi
